version: "3"

services:
  database:
    image: postgres:latest
    container_name: database-moviemania
    restart: always
    environment:
      POSTGRES_DB: dbmoviemania
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - /data